# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdaa8a9932eb32ee6a92b16a056fb1886a8b8a9b7519c2007d9157e717711df7e16eeee7a8ef94664d836cf9bec907f066c5dae77e32d184c119f7f51d5b5719

test:
  secret_key_base: 32dad31ee432c7d8621cad35abaaf5b2883ae559ecd3905c6b4ed04fde1568cb2e97adc1c5905dc6efc18f5fb8cda325123f8ae856f8d4f1cdd4b6bf274c7b5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
